# Configuration file for Mentions plugin
# Supports HEX colors using &#RRGGBB or MiniMessage format
prefix: "&8[&a&lMentions&8] &r"

mention-prefix: "@" # Etc.: @XAP3Y

gui-enable: true # Allow GUI to manage mention notifications using /mentions

# Variables:
# %player% - name of the player who mentioned you
# %target% - name of the player who was mentioned

actionbar:
    enabled: true
    message: "&a%player% &7mentioned you!"

sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_BELL" # https://helpch.at/docs/1.20/org/bukkit/Sound.html
    volume: 1.0 # 0.0 - 1.0
    pitch: 1.0 # 0.5 - 2.0

# Chat formatting, does not send a new message.
# Etc. Hi XAP3Y, how are you? -> Hi &a&lXAP3Y&r, how are you?
chat:
    enabled: true
    replace: "&a&l%nick%&r"

title:
    enabled: true
    title: "&a%player%" # Empty string = no title
    subtitle: "&7tě zmínil v chatu!" # Empty string = no subtitle
    fade-in: 20 # ticks
    stay: 60 # ticks
    fade-out: 20 # ticks